lesson_02/blog/app.py
from flask import Flask
from lesson_02.blog.user.views import user
from lesson_02.blog.report.views import report

def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprints(app)
    return app


def register_blueprints(app: Flask):
    app.register_blueprint(user)
    app.register_blueprint(report)

lesson_02/blog/report/views.py
from flask import Blueprint, render_template, redirect

report = Blueprint('report', __name__, url_prefix='/reports', static_folder ='../static')

REPORTS = {
    1: 'Animals',
    2: 'Water',
    3: 'Flame',
    4: 'Cosmos',
    5: 'Sea'
}


@report.route('/')
def report_list():
    return render_template(
        'reports/list.html',
        reports=REPORTS,
    )


@report.route('/<int:pk>')
def get_report(pk: int):
    try:
        report_name = REPORTS[pk]
    except KeyError:
        #raise NotFound(f'User id {pk} not found')
        return redirect('/reports/')
    return render_template(
        'reports/details.html',
        report_name=report_name,
    )

lesson_02/blog/user/views.py
from flask import Blueprint, render_template, redirect
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, url_prefix='/users', static_folder ='../static')

USERS = {
    1: 'Mary',
    2: 'Robert',
    3: 'Mark',
}

@user.route('/')
def user_list():
    return render_template(
        'users/list.html',
        users=USERS,
    )


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        #raise NotFound(f'User id {pk} not found')
        return redirect('/users/')
    return render_template(
        'users/details.html',
        user_name=user_name,
    )

lesson_02/blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
  {% block body %}{% endblock %}
</div>

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossorigin="anonymous"></script>
{% endblock %}
  </body>
</html>

lesson_02/blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Main </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.user_list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

lesson_02/blog/templates/reports/details.html
{% extends 'base.html' %}

{% block title %}
    Report detail
{% endblock %}

{% block body %}
    <h1>{{ report_name }}</h1>
{% endblock %}

lesson_02/blog/templates/reports/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>List of reports</h1>
            {% for report_id in reports %}
                <ul>
                    <li><a href="{{ url_for('report.get_report', pk=report_id) }}">{{ reports[report_id] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>

{% endblock %}

lesson_02/blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    Users detail
{% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>
{% endblock %}

lesson_02/blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>List of Users</h1>
            {% for user_id in users %}
                <ul>
                    <li><a href="{{ url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>

{% endblock %}